apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: packer-build
  namespace: default
spec:
  results:
  - name: image
  params:
  - default: ./
    description: The build context used by Kaniko.
    name: CONTEXT
    type: string
  - default: harbor.vrabbi.cloud/library/vsphere-packer:0.0.1
    description: The image on which builds will run (default is 0.0.1)
    name: BUILDER_IMAGE
    type: string
  - default: vsphere-creds
    description: secret containing vsphere connection details
    type: string
    name: vsphere-secret
  steps:
  - args:
    - "./build.sh deploy"
    image: $(params.BUILDER_IMAGE)
    name: build-and-push
    resources: {}
    securityContext:
      runAsUser: 0
    workingDir: $(workspaces.source.path)
    envFrom:
      - secretRef:
          name: $(params.vsphere-secret)
  workspaces:
  - name: source
