#@ load("@ytt:data", "data")
---
kind: Secret
apiVersion: v1
metadata:
  name: vsphere-creds
stringData:
  vcenter_username: #@ data.values.vcenter_username
  vcenter_password: #@ data.values.vcenter_password
  ssh_username: #@ data.values.vm_user
  ssh_password: #@ data.values.vm_password
type: Opaque
