#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:base64", "base64")

#@ def vsphere_creds():
vSphereUser: #@ data.values.vcenter_username
vSpherePassword: #@ data.values.vcenter_password
vSphereServer: #@ data.values.vcenter_fqdn
vSphereAllowUnverifiedSSL: #@ data.values.vcenter_insecure
#@ end
---
apiVersion: v1
data:
  credentials: #@ base64.encode(yaml.encode(vsphere_creds()))
kind: Secret
metadata:
  name: tf-vsphere-creds
  namespace: terraform
type: Opaque
---
apiVersion: v1
data:
  credentials: #@ base64.encode(yaml.encode(vsphere_creds()))
kind: Secret
metadata:
  name: tf-vsphere-creds
  namespace: default
type: Opaque

