apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: vsphere
spec:
  provider: vsphere
  region: cn-beijing
  credentials:
    source: Secret
    secretRef:
      namespace: terraform
      name: tf-vsphere-creds
      key: credentials
